[package]
name = "cargo-release"
version = "0.16.4-alpha.0"
authors = ["Ning Sun <sunng@pm.me>", "Ed Page <eopage@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Cargo subcommand for you to smooth your release process."
keywords = ["cargo"]
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/crate-ci/cargo-release"
readme = "README.md"
edition = "2018"
exclude = [
    "docs/**",
    "README.md",
    "CHANGELOG.md",
    "hook.sh",
    "release.toml",
    ".github/**",
]

[dependencies]
cargo_metadata = "0.14"
crates-index = "0.17"
toml = {version = "0.5", default-features = false}
toml_edit = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
semver = "1.0"
quick-error = "2.0"
regex = "1.0"
bstr = "0.2.8"
termcolor = "1.0"
maplit = "1.0"
chrono = "0.4"
dirs-next = "2.0"
ignore = "0.4"
difflib = "0.4"
itertools = "0.9"
once_cell = "1.2.0"
structopt = {version = "0.3.0", default-features = false}
clap = { version = "2", default-features = false }
clap-cargo = { version = "0.6", features = ["cargo_metadata"] }
log = "0.4"
env_logger = "0.8"

[dev-dependencies]
assert_fs = "1.0"
predicates = "1.0"
